---
# PostgreSQL for Airflow metadata (EMBEDDED - Only deployed if standalone postgres not in ENABLED_SERVICES)
# If you have postgres in ENABLED_SERVICES, this section will be skipped and Airflow will use standalone postgres
# To use standalone postgres:
#   1. Add 'postgres' to ENABLED_SERVICES
#   2. Deploy postgres first: ./k8s/scripts/postgres.sh deploy
#   3. Create airflow database: ./k8s/scripts/postgres.sh create-db airflow
#   4. Create airflow user: ./k8s/scripts/postgres.sh create-user airflow airflow
#   5. Grant privileges: ./k8s/scripts/postgres.sh grant airflow airflow
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
  labels:
    app: airflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: airflow-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
  labels:
    app: airflow-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: airflow-postgres

---
# Airflow Webserver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    component: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: webserver
  template:
    metadata:
      labels:
        app: airflow
        component: webserver
    spec:
      initContainers:
      - name: init-db
        image: apache/airflow:2.7.0-python3.9
        command:
        - bash
        - -c
        - |
          airflow db init
          airflow users create \
            --username admin \
            --password admin \
            --firstname Admin \
            --lastname User \
            --role Admin \
            --email admin@example.com || true
        env:
        - name: POSTGRES_HOST
          value: "airflow-postgres"  # Change to "postgres" if using standalone postgres service
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@$(POSTGRES_HOST):5432/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
      containers:
      - name: webserver
        image: apache/airflow:2.7.0-python3.9
        command:
        - airflow
        - webserver
        env:
        - name: POSTGRES_HOST
          value: "airflow-postgres"  # Change to "postgres" if using standalone postgres service
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@$(POSTGRES_HOST):5432/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
          value: "True"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

---
# Airflow Scheduler
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      containers:
      - name: scheduler
        image: apache/airflow:2.7.0-python3.9
        command:
        - airflow
        - scheduler
        env:
        - name: POSTGRES_HOST
          value: "airflow-postgres"  # Change to "postgres" if using standalone postgres service
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@$(POSTGRES_HOST):5432/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

---
# Airflow Webserver Service
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    component: webserver
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: airflow
    component: webserver
