---
# MongoDB Standalone Service
# A production-ready NoSQL document database for flexible data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  # MongoDB configuration optimized for development/local use
  mongod.conf: |
    # Storage
    storage:
      dbPath: /data/db
      journal:
        enabled: true
      wiredTiger:
        engineConfig:
          cacheSizeGB: 1  # Adjust based on memory allocation
        collectionConfig:
          blockCompressor: snappy

    # Network
    net:
      port: 27017
      bindIp: 0.0.0.0
      maxIncomingConnections: 100

    # Security
    security:
      authorization: enabled

    # Logging
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
      verbosity: 0

    # Operation Profiling
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "mongodb"
  MONGO_INITDB_DATABASE: "admin"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:8.0
        envFrom:
        - secretRef:
            name: mongodb-secret
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        - name: logs
          mountPath: /var/log/mongodb
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - mongosh
            - --quiet
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mongosh
            - --quiet
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongodb-pvc
      - name: config
        configMap:
          name: mongodb-config
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
    nodePort: 30017
  selector:
    app: mongodb
