---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
data:
  main.cf: |
    myhostname = postfix
    mydomain = example.com
    myorigin = $mydomain
    inet_interfaces = all
    inet_protocols = ipv4
    mydestination = $myhostname, localhost.$mydomain, localhost
    relayhost =
    mynetworks = 0.0.0.0/0
    mailbox_size_limit = 0
    recipient_delimiter = +

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
      - name: postfix
        image: catatnight/postfix:latest
        env:
        - name: maildomain
          value: "example.com"
        - name: smtp_user
          value: "user:password"
        ports:
        - containerPort: 25
          name: smtp
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  type: NodePort
  ports:
  - port: 25
    targetPort: 25
    name: smtp
    nodePort: 30025
  selector:
    app: postfix
