---
# Spark Master Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark
    component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      component: master
  template:
    metadata:
      labels:
        app: spark
        component: master
    spec:
      enableServiceLinks: false
      containers:
      - name: spark-master
        image: apache/spark:3.5.3
        command: ["/opt/spark/bin/spark-class"]
        args: ["org.apache.spark.deploy.master.Master", "--host", "0.0.0.0", "--port", "7077", "--webui-port", "8080"]
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "true"
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 7077
          name: master
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10

---
# Spark Master Service
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app: spark
    component: master
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  - port: 7077
    targetPort: 7077
    name: master
  selector:
    app: spark
    component: master

---
# Spark Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark
      component: worker
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      enableServiceLinks: false
      containers:
      - name: spark-worker
        image: apache/spark:3.5.3
        command: ["/opt/spark/bin/spark-class"]
        args: ["org.apache.spark.deploy.worker.Worker", "--webui-port", "8081", "--memory", "1G", "--cores", "1", "spark://spark-master:7077"]
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "true"
        ports:
        - containerPort: 8081
          name: web
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10

---
# Spark Worker Service
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  labels:
    app: spark
    component: worker
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    name: web
  selector:
    app: spark
    component: worker
