---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zincsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zincsearch
  labels:
    app: zincsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zincsearch
  template:
    metadata:
      labels:
        app: zincsearch
    spec:
      containers:
      - name: zincsearch
        image: public.ecr.aws/zinclabs/zincsearch:latest
        env:
        - name: ZINC_FIRST_ADMIN_USER
          value: "admin"
        - name: ZINC_FIRST_ADMIN_PASSWORD
          value: "admin"
        - name: ZINC_DATA_PATH
          value: "/data"
        ports:
        - containerPort: 4080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4080
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zincsearch-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: zincsearch
  labels:
    app: zincsearch
spec:
  type: NodePort
  ports:
  - port: 4080
    targetPort: 4080
    name: http
  selector:
    app: zincsearch
